### PR TITLE
small fix for wrong instanceof

### PR DESCRIPTION
**Pull request by a-lugovskoy**
small fix for wrong instanceof

### CODE REVIEW

**Comment by doom369** [comment]
@a-lugovskoy could you please explain why do think this commit fixes something?

**Comment by a-lugovskoy** [comment]
It's not critical(it's not bug), but my fix is "good tone" and i think it's more correct.

**Comment by doom369** [comment]
If it is not bug - why would you name this PR as `fix` and `wrong`?

`but my fix is "good tone" and i think it's more correct.`

You are wrong. Your approach is harder to read and that is more important - much slower.

**Comment by a-lugovskoy** [comment]
> If it is not bug - why would you name this PR as fix and wrong?

>>but my fix is "good tone" and i think it's more correct.

Maybe you are right. I spoke incorrectly. 

> and waht is more important - much slower.

About this, i don't think so. 
Method "isInstance" is the dynamic equivalent of the Java language instanceof operator. [Java Doc](http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Class.html#isInstance%28java.lang.Object%29)
And "time tests" show the same result.

**Comment by doom369** [comment]
`i don't think so.`

There is no need for guess. Just look in generated byte code.

**Comment by a-lugovskoy** [comment]
> There is no need for guess. Just look in generated byte code.

Ok. Thank you)

**Pull request closed without merging**
