### PR TITLE
Optimizartion in ByteBufUtil and in Session sendMessageTo*

### PR DESCRIPTION
**Pull request by artem-v**
* ``ByteBufUtil``: no need to depend on ``Channel`` or ``ChannelHandlerContext``, use just ``PooledByteBufAllocator.DEFAULT`` for allocation; this caused most changes.

* ``Session``: familty of _sendMessageTo()_ methods seems like renders idea of sending one message to different channels; sort of 'multicast'; downside is that same msg is being constructed again and again while looping on channels; an idea of refactoring -- create only one message, send it in a loop by just reseting reader index when iterating.

### CODE REVIEW

**Comment by doom369** [comment]
@artem-v could you please submit ByteBuf change as separate pull request? This is nice catch, I'm ready to accept it.

Regarding changes to `sendMessageTo` I have few concers:

- only 10% of Blynk users have multiple hardware;
- more hardware less users;
- proposed change has additional allocation - `targetChannels`;
- execution flow a bit longer;

I can't accept that without micro benchmark that shows no degradation for 1 hardware channel and for 2 hardware channels.

**Comment by artem-v** [comment]
@doom369 regarding ByteBufUItil -- created PR https://github.com/blynkkk/blynk-server/pull/181

**Comment by doom369** [comment]
@artem-v thanks a lot. Merged.

**Comment by artem-v** [comment]
@doom369 
> only 10% of Blynk users have multiple hardware

I saw that ``Session``provides set of app channels as well. Though I don't know what percentage of users have multiple app channels per session, this PR just set a fix for problem in general form. It just allows to not be concerned about channels _multipleness_ .

> more hardware less users

Sorry, didn't get it. Can you please explain?

**Comment by doom369** [comment]
@artem-v yes, I understand what you have in mind.

`Though I don't know what percentage of users have multiple app channels per session`

For Blynk 90% of users have 1 to 1 connections. 

> Sorry, didn't get it. Can you please explain?

I mean we have only few users with many hardware.

I can say for sure that in proposed solution there is 1 additional allocation vs original solution. Take in mind that those method is the VERY HOT method.

**Comment by artem-v** [comment]
Created PR https://github.com/blynkkk/blynk-server/pull/184 for benchmarking _sendMessageToHardware_ 1,2  channels.

**Pull request closed without merging**
